### ISSUE TITLE
Encoder and Decoder

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [frasertweedale/hs-fresnel#1]
I want to decode multiple DXF files to native haskell data, make some changes, and then encode them back to DXF files. (DXF is a CAD file format to define geometries)
What is your opinion on being able to accomplish this with your library?
I have attached a sample DXF file for reference.
[dog.txt](https://github.com/frasertweedale/hs-fresnel/files/3709250/dog.txt)

**Comment by frasertweedale** [comment]
@BebeSparkelSparkel hs-fresnel is experimental.  If you give it a go and get good results, great, let me know and send examples :)  But you may have a much better time with a parsing library like attoparsec.  For serialisation, I'm not sure what the best library options would be (hand-rolling might be fine).

**Comment by BebeSparkelSparkel** [comment]
Thanks for the advice. I have been using megaparsec, but thought there might be a better solution.
