### ISSUE TITLE
Parsing Errors

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [frasertweedale/hs-fresnel#2]
I do not see anyway to have detailed parser errors with this. Is this possible?

**Comment by BebeSparkelSparkel** [comment]
Have you looked at https://www.reddit.com/r/haskell/comments/ej15ar/basic_error_reporting_for_optics/

**Comment by frasertweedale** [comment]
Nope, they're prisms, so no errors.  Fresnel is just an experiment.  Feel free to fork it and take it further!

**Comment by BebeSparkelSparkel** [comment]
Thanks, good idea
